ecommerce/demo/urls.py
from django.urls import path
from . import views

app_name="demo"

urlpatterns = [
    path('', views.home, name="home"),
    path('categories/', views.category),
    path('product_by_category/<slug:category>', views.product_by_category, name="product_by_category"),
    path('<slug:slug>/', views.product_detail, name="product_detail")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from ecommerce.drf.views import AllProductsViewsets

router = routers.DefaultRouter()
router.register(
    r'api', AllProductsViewsets, basename="allproducts"
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo/', include(("ecommerce.demo.urls", "demo"), namespace="demo")),
    path("", include(router.urls)),
]

ecommerce/demo/views.py
from django.shortcuts import render
from ecommerce.inventory import models
from django.db.models import Count
from django.contrib.postgres.aggregates import ArrayAgg


def home(request):
    return render(request, "index.html")


def category(request):
    
    data = models.Category.objects.all()

    return render(request, "categories.html", {"data": data})


def product_by_category(request, category):
    
    data = models.Product.objects.filter(category__name=category).filter(
        product__is_default=True).values(
        "id", "name", "slug", "created_at", "category__name", "product__store_price")

    return render(request, "product_by_category.html", {"data": data})


def product_detail(request, slug):

    filter_arguments = []

    if request.GET:
        for value in request.GET.values():
            filter_arguments.append(value)

        data = models.ProductInventory.objects.filter(product__slug=slug).filter(
            attribute_values__attribute_value__in=filter_arguments).annotate(
            num_tags=Count('attribute_values')).filter(num_tags=len(filter_arguments)
            ).values(
            "id", "sku", "product__name", "store_price", "product_inventory__units"
            ).annotate(field_a=ArrayAgg("attribute_values__attribute_value")).get()

        # print(data)
        
    else:
        data = models.ProductInventory.objects.filter(product__slug=slug).filter(
            is_default=True).values(
            "id", "sku", "product__name", "store_price", "product_inventory__units"
            ).annotate(field_a=ArrayAgg("attribute_values__attribute_value")).get()
        
        # print(data)

    att_val_name = models.ProductInventory.objects.filter(product__slug=slug
        ).distinct().values(
        "attribute_values__product_attribute__name", "attribute_values__attribute_value")

    att_name = models.ProductTypeAttribute.objects.filter(
        product_type__product_type__product__slug=slug).distinct().values(
        "product_attribute__name")
 
    return render(request, "product_detail.html", 
                {"data": data, "att_val_name": att_val_name,"att_name": att_name})

ecommerce/demo/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <title>Hello, world!</title>
  </head>
  <body>
    {% block content %}

    {% endblock content %}
  </body>
</html>

ecommerce/demo/templates/categories.html
{% extends 'base.html' %}
{% block title %}Categories{% endblock title %}

{% block content %}
    <h1>Categories</h1>
    {% for d in data %}
        <a href="{% url 'demo:product_by_category' category=d.slug %}">
            {{d.name}}
        </a>
    {% endfor %}
{% endblock content %}

ecommerce/demo/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Homepage</h1>

<a href="categories/">Categories</a>
{% endblock content %}

ecommerce/demo/templates/product_by_category.html
{% extends 'base.html' %}
{% block title %}Product By Category{% endblock %}

{% block content %}
<h1>Products in Category</h1>
<ul>
    {% for d in data %}
        <li class="text-capitalize">
            {{d.name}} [<a href="{% url 'demo:product_detail' slug=d.slug %}">view</a>]
        </li>
        <ul class="list-unstyled">
        <li>ID: {{d.id}}</li>
        <li>Price: ${{d.product__store_price}}</li>
        <br />
        </ul>
    {% endfor %}
</ul>
{% endblock content %}
    

ecommerce/demo/templates/product_detail.html
{% extends 'base.html' %}

{% block title %}Product Detail{% endblock %}

{% block content %}
<h1>Product detail</h1>
<ul>
    <li class="text-capitalize">
    {{data.product__name}}
    </li>
    <ul class="list-unstyled">
    <li>SKU: {{data.sku}}
    <li>Price: ${{data.store_price}}</li>
    <li>{{data.attribute_values__attribute_value}}</li>
    <li>Stock: {{data.product_inventory__units}}</li>
    </ul>
</ul>

<ul>
  {% for y in att_name %}
    <li class="text-capitalize">
    {{y.product_attribute__name}}
    <ul>
      {% for a in att_val_name %}
        {% if a.attribute_values__product_attribute__name == y.product_attribute__name  %}
        <li class="text-capitalize">
            {% if a.attribute_values__attribute_value in data.field_a %}
            <div id="target-{{a.attribute_values__attribute_value}}" class="selected fw-bold" data-attribute="{{y.product_attribute__name}}" value="{{a.attribute_values__attribute_value}}">{{a.attribute_values__attribute_value}}</div>
            {% else %}
            <div id="target-{{a.attribute_values__attribute_value}}" class="" data-attribute="{{y.product_attribute__name}}" value="{{a.attribute_values__attribute_value}}">{{a.attribute_values__attribute_value}}</div>
            {% endif %}
        </li>
        {% endif %}
      {% endfor %}
    </ul>
    </li>
  {% endfor %}
</ul>

<script>
    var d = {}
    
    let textBoxes = document.querySelectorAll('[id^=target')

    let e = 0
    let f = textBoxes.length

    for (let i in textBoxes) {
        if (e < f) {
            if (textBoxes[i].classList.contains("selected")) {
                d[textBoxes[i].getAttribute('data-attribute')] = textBoxes[i].getAttribute('value')
            }
        } else {
            break
        }   
        e++
    }

    document.addEventListener('click', function(e) {
        let value = e.target.getAttribute('value')
        d[e.target.getAttribute('data-attribute')] = e.target.getAttribute('value')
        let querystring = buildUrlWithParams(d)
        let url = window.location.href.split('?')[0]
        window.location.href = url + "?" + querystring
    }, false)

    function buildUrlWithParams(data) {
        var searchparams = []
        for (var d in data){
            searchparams.push(d + '=' + data[d])
        }
        return searchparams.join('&')
  }
</script>
{% endblock content %}